name: Python

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install OS dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install portaudio19-dev
            sudo apt install openjdk-8-jdk
            sudo wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
            sudo echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
            sudo apt update
            sudo apt install neo4j
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install jdk8
            choco install neo4j-community -version 3.5.1
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
